# This workflow will build a package using Gradle

name: Gradle Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v0.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Build with Gradle
        run: gradle build
